### ISSUE TITLE
What OS do we need to have on our device?

### ISSUE THREAD

**Issue by mirsaeedi** [gaurav-karna/Ocularis#1]
1. Windows IoT Core
2. Linux

**Comment by mirsaeedi** [comment]
I believe both of them works. However, it would be better to go with Windows IoT core because it's a Microsoft challenge.

But there are some technical things we should consider:

1. Windows IoT Core supports a smaller set of sensor and devices compared to Linux. The List of all supported devices is [here](https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/hardwarecompatlist).
2. Choosing Windows IoT lets us use .NET with more ease and less trouble. Although .NET core runs on Linux, I guess there are some difficulties around connecting Camera and Microphone using .NET in Linux. I found some open source libraries but there is no official support. [+](https://github.com/unosquare/raspberryio),[+](https://github.com/techyian/MMALSharp)

**Comment by gaurav-karna** [comment]
I agree that Windows IoT is better since it is a Microsoft challenge.

However, should we not take more factors into account? For example, Linux is inherently more scalable than Windows IoT, and so it will also support a larger number of cheaper devices, which makes it more accessible to more people. Also, since we need to take the business aspect into account - we can also make the case that the cost of production is also lowered by using the Linux OS - increasing profits.

Nevertheless, you do know more about C# and .NET framework. I agree that it intertwines better with Windows IoT. To summarize, I guess it's two issues I would be concerned with:
- Cost efficiency ---> in terms of using Linux (cheaper to scale to more devices ?)
- Accessibility to 3rd party developers ---> Windows IoT is obviously less prevalent than Linux, and so open-sourcing to 3rd party developers will not be as effective if we do it on IoT. 

Let me know what you think.
